//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitService
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestClientMaster
    {
        public int requestID { get; set; }
        public int clientID { get; set; }
        public Nullable<int> masterID { get; set; }
    
        public virtual request request { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
